name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose -f ./ci/docker-compose.yml build

    - name: Run tests
      run: docker-compose -f ./ci/docker-compose.yml run test
