name: Run tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose -f ./ci/docker-compose.yml build

    - name: Run tests
      run: docker-compose -f ./ci/docker-compose.yml run test

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: allure
        path: allure-results


  allure:
    name: Generate Allure Report
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Download math result for job 1
        uses: actions/download-artifact@v3
        with:
          name: allure
      - shell: bash
        run: |
          value=`unzip allure.zip -d ./allure-results`      

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
